const allData = [
  {
    id: 1,
    image:
      "https://img.favpng.com/9/10/1/clothing-victorian-fashion-gown-fashion-costume-design-png-favpng-FUBv97CHvzgt8zWtzYrSJQdXy.jpg",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design ",
    price: 152,
    fav: false,
    number: 0,
    categorie: "BestSeller",
  },
  {
    id: 2,
    image:
      "https://thumbnail.imgbin.com/15/12/4/imgbin-victorian-era-1880s-bustle-victorian-fashion-clothing-victorian-woman-tyyXbAdh24WxGfVTE9pqBfUGd_t.jpg",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 123,
    fav: false,
    number: 0,
    categorie: "BestSeller",
  },
  {
    id: 3,
    image:
      "https://img.favpng.com/9/10/1/clothing-victorian-fashion-gown-fashion-costume-design-png-favpng-FUBv97CHvzgt8zWtzYrSJQdXy.jpg",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 111,
    fav: false,
    number: 0,
    categorie: "BestSeller",
  },
  {
    id: 4,
    image:
      "https://thumbnail.imgbin.com/15/12/4/imgbin-victorian-era-1880s-bustle-victorian-fashion-clothing-victorian-woman-tyyXbAdh24WxGfVTE9pqBfUGd_t.jpg",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 342,
    fav: false,
    number: 0,
    categorie: "BestSeller",
  },
  {
    id: 5,
    image:
      "https://img.favpng.com/9/10/1/clothing-victorian-fashion-gown-fashion-costume-design-png-favpng-FUBv97CHvzgt8zWtzYrSJQdXy.jpg",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 222,
    fav: false,
    number: 0,
    categorie: "BestSeller",
  },
  {
    id: 6,
    image:
      "https://thumbnail.imgbin.com/15/12/4/imgbin-victorian-era-1880s-bustle-victorian-fashion-clothing-victorian-woman-tyyXbAdh24WxGfVTE9pqBfUGd_t.jpg",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 144,
    fav: false,
    number: 0,
    categorie: "BestSeller",
  },
  {
    id: 7,
    image:
      "https://img.favpng.com/9/10/1/clothing-victorian-fashion-gown-fashion-costume-design-png-favpng-FUBv97CHvzgt8zWtzYrSJQdXy.jpg",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 122,
    fav: false,
    number: 0,
    categorie: "BestSeller",
  },
  {
    id: 8,
    image:
      "https://thumbnail.imgbin.com/15/12/4/imgbin-victorian-era-1880s-bustle-victorian-fashion-clothing-victorian-woman-tyyXbAdh24WxGfVTE9pqBfUGd_t.jpg",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 321,
    fav: false,
    number: 0,
    categorie: "BestSeller",
  },
  {
    id: 9,
    image:
      "https://w1.pngwing.com/pngs/345/800/png-transparent-top-hat-victorian-fashion-clothing-dress-costume-vintage-clothing-evening-gown-riding-habit.png",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 321,
    new: "Sales -5 %",
    fav: false,
    number: 0,
    color: "productCard-flex-sale",
    categorie: "Outlet",
  },
  {
    id: 10,
    image:
      "https://w7.pngwing.com/pngs/507/528/png-transparent-paper-doll-victorian-era-dress-dress-fashion-vintage-clothing-doll.png",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 453,
    new: "Sales -3 %",
    fav: false,
    number: 0,
    color: "productCard-flex-sale",
    categorie: "Outlet",
  },
  {
    id: 11,
    image:
      "https://w1.pngwing.com/pngs/345/800/png-transparent-top-hat-victorian-fashion-clothing-dress-costume-vintage-clothing-evening-gown-riding-habit.png",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 321,
    new: "Sales -12 %",
    fav: false,
    number: 0,
    color: "productCard-flex-sale",
    categorie: "Outlet",
  },
  {
    id: 12,
    image:
      "https://w7.pngwing.com/pngs/507/528/png-transparent-paper-doll-victorian-era-dress-dress-fashion-vintage-clothing-doll.png",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 676,
    new: "Sales -12 %",
    fav: false,
    number: 0,
    color: "productCard-flex-sale",
    categorie: "Outlet",
  },
  {
    id: 13,
    image:
      "https://w1.pngwing.com/pngs/345/800/png-transparent-top-hat-victorian-fashion-clothing-dress-costume-vintage-clothing-evening-gown-riding-habit.png",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 75,
    new: "Sales -1 %",
    fav: false,
    number: 0,
    color: "productCard-flex-sale",
    categorie: "Outlet",
  },
  {
    id: 14,
    image:
      "https://w7.pngwing.com/pngs/507/528/png-transparent-paper-doll-victorian-era-dress-dress-fashion-vintage-clothing-doll.png",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 154,
    new: "Sales -2 %",
    fav: false,
    number: 0,
    color: "productCard-flex-sale",
    categorie: "Outlet",
  },
  {
    id: 15,
    image:
      "https://w1.pngwing.com/pngs/345/800/png-transparent-top-hat-victorian-fashion-clothing-dress-costume-vintage-clothing-evening-gown-riding-habit.png",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 132,
    new: "Sales -25 %",
    fav: false,
    number: 0,
    color: "productCard-flex-sale",
    categorie: "Outlet",
  },
  {
    id: 16,
    image:
      "https://w7.pngwing.com/pngs/507/528/png-transparent-paper-doll-victorian-era-dress-dress-fashion-vintage-clothing-doll.png",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 157,
    new: "Sales -22 %",
    fav: false,
    number: 0,
    color: "productCard-flex-sale",
    categorie: "Outlet",
  },
  {
    id: 17,
    image:
      "https://w7.pngwing.com/pngs/240/957/png-transparent-marie-antoinette-18th-century-france-french-revolution-1700s-france-hat-fashion-clothing-accessories.png",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 157,
    fav: false,
    number: 0,
    new: "New",
    color: "productCard-flex-new",
    categorie: "NewArrivals",
  },
  {
    id: 18,
    image:
      "https://e7.pngegg.com/pngimages/79/200/png-clipart-18th-century-fashion-plate-france-clothing-france-fashion-france-thumbnail.png",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 154,
    fav: false,
    number: 0,
    new: "New",
    color: "productCard-flex-new",
    categorie: "NewArrivals",
  },
  {
    id: 19,
    image:
      "https://w7.pngwing.com/pngs/240/957/png-transparent-marie-antoinette-18th-century-france-french-revolution-1700s-france-hat-fashion-clothing-accessories.png",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 140,
    fav: false,
    number: 0,
    new: "New",
    color: "productCard-flex-new",
    categorie: "NewArrivals",
  },
  {
    id: 20,
    image:
      "https://e7.pngegg.com/pngimages/79/200/png-clipart-18th-century-fashion-plate-france-clothing-france-fashion-france-thumbnail.png",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 110,
    fav: false,
    number: 0,
    new: "New",
    color: "productCard-flex-new",
    categorie: "NewArrivals",
  },
  {
    id: 21,
    image:
      "https://w7.pngwing.com/pngs/240/957/png-transparent-marie-antoinette-18th-century-france-french-revolution-1700s-france-hat-fashion-clothing-accessories.png",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 140,
    fav: false,
    number: 0,
    new: "New",
    color: "productCard-flex-new",
    categorie: "NewArrivals",
  },
  {
    id: 22,
    image:
      "https://e7.pngegg.com/pngimages/79/200/png-clipart-18th-century-fashion-plate-france-clothing-france-fashion-france-thumbnail.png",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 150,
    fav: false,
    number: 0,
    new: "New",
    color: "productCard-flex-new",
    categorie: "NewArrivals",
  },
  {
    id: 23,
    image:
      "https://w7.pngwing.com/pngs/240/957/png-transparent-marie-antoinette-18th-century-france-french-revolution-1700s-france-hat-fashion-clothing-accessories.png",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 150,
    fav: false,
    number: 0,
    new: "New",
    color: "productCard-flex-new",
    categorie: "NewArrivals",
  },
  {
    id: 2,
    image:
      "https://e7.pngegg.com/pngimages/79/200/png-clipart-18th-century-fashion-plate-france-clothing-france-fashion-france-thumbnail.png",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 120,
    fav: false,
    number: 0,
    new: "New",
    color: "productCard-flex-new",
    categorie: "NewArrivals",
  },
];

export default allData;
