const NewArrivas = [
  {
    id: 17,
    image:
      "https://w7.pngwing.com/pngs/240/957/png-transparent-marie-antoinette-18th-century-france-french-revolution-1700s-france-hat-fashion-clothing-accessories.png",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 157,
    fav: false,
    number: 0,
    new: "New",
    color: "productCard-flex-new",
    categorie: "NewArrivals",
  },
  {
    id: 18,
    image:
      "https://e7.pngegg.com/pngimages/79/200/png-clipart-18th-century-fashion-plate-france-clothing-france-fashion-france-thumbnail.png",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 154,
    fav: false,
    number: 0,
    new: "New",
    color: "productCard-flex-new",
    categorie: "NewArrivals",
  },
  {
    id: 19,
    image:
      "https://w7.pngwing.com/pngs/240/957/png-transparent-marie-antoinette-18th-century-france-french-revolution-1700s-france-hat-fashion-clothing-accessories.png",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 140,
    fav: false,
    number: 0,
    new: "New",
    color: "productCard-flex-new",
    categorie: "NewArrivals",
  },
  {
    id: 20,
    image:
      "https://e7.pngegg.com/pngimages/79/200/png-clipart-18th-century-fashion-plate-france-clothing-france-fashion-france-thumbnail.png",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 110,
    fav: false,
    number: 0,
    new: "New",
    color: "productCard-flex-new",
    categorie: "NewArrivals",
  },
  {
    id: 21,
    image:
      "https://w7.pngwing.com/pngs/240/957/png-transparent-marie-antoinette-18th-century-france-french-revolution-1700s-france-hat-fashion-clothing-accessories.png",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 140,
    fav: false,
    number: 0,
    new: "New",
    color: "productCard-flex-new",
    categorie: "NewArrivals",
  },
  {
    id: 22,
    image:
      "https://e7.pngegg.com/pngimages/79/200/png-clipart-18th-century-fashion-plate-france-clothing-france-fashion-france-thumbnail.png",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 150,
    fav: false,
    number: 0,
    new: "New",
    color: "productCard-flex-new",
    categorie: "NewArrivals",
  },
  {
    id: 23,
    image:
      "https://w7.pngwing.com/pngs/240/957/png-transparent-marie-antoinette-18th-century-france-french-revolution-1700s-france-hat-fashion-clothing-accessories.png",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 150,
    fav: false,
    number: 0,
    new: "New",
    color: "productCard-flex-new",
    categorie: "NewArrivals",
  },
  {
    id: 24,
    image:
      "https://e7.pngegg.com/pngimages/79/200/png-clipart-18th-century-fashion-plate-france-clothing-france-fashion-france-thumbnail.png",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 120,
    fav: false,
    number: 0,
    new: "New",
    color: "productCard-flex-new",
    categorie: "NewArrivals",
  },
];
export default NewArrivas;
