const OutletData = [
  {
    id: 9,
    image:
      "https://w1.pngwing.com/pngs/345/800/png-transparent-top-hat-victorian-fashion-clothing-dress-costume-vintage-clothing-evening-gown-riding-habit.png",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 321,
    new: "Sales -5 %",
    fav: false,
    number: 0,
    color: "productCard-flex-sale",
    categorie: "Outlet",
  },
  {
    id: 10,
    image:
      "https://w7.pngwing.com/pngs/507/528/png-transparent-paper-doll-victorian-era-dress-dress-fashion-vintage-clothing-doll.png",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 453,
    new: "Sales -3 %",
    fav: false,
    number: 0,
    color: "productCard-flex-sale",
    categorie: "Outlet",
  },
  {
    id: 11,
    image:
      "https://w1.pngwing.com/pngs/345/800/png-transparent-top-hat-victorian-fashion-clothing-dress-costume-vintage-clothing-evening-gown-riding-habit.png",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 321,
    new: "Sales -12 %",
    fav: false,
    number: 0,
    color: "productCard-flex-sale",
    categorie: "Outlet",
  },
  {
    id: 12,
    image:
      "https://w7.pngwing.com/pngs/507/528/png-transparent-paper-doll-victorian-era-dress-dress-fashion-vintage-clothing-doll.png",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 676,
    new: "Sales -12 %",
    fav: false,
    number: 0,
    color: "productCard-flex-sale",
    categorie: "Outlet",
  },
  {
    id: 13,
    image:
      "https://w1.pngwing.com/pngs/345/800/png-transparent-top-hat-victorian-fashion-clothing-dress-costume-vintage-clothing-evening-gown-riding-habit.png",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 75,
    new: "Sales -1 %",
    fav: false,
    number: 0,
    color: "productCard-flex-sale",
    categorie: "Outlet",
  },
  {
    id: 14,
    image:
      "https://w7.pngwing.com/pngs/507/528/png-transparent-paper-doll-victorian-era-dress-dress-fashion-vintage-clothing-doll.png",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 154,
    new: "Sales -2 %",
    fav: false,
    number: 0,
    color: "productCard-flex-sale",
    categorie: "Outlet",
  },
  {
    id: 15,
    image:
      "https://w1.pngwing.com/pngs/345/800/png-transparent-top-hat-victorian-fashion-clothing-dress-costume-vintage-clothing-evening-gown-riding-habit.png",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 132,
    new: "Sales -25 %",
    fav: false,
    number: 0,
    color: "productCard-flex-sale",
    categorie: "Outlet",
  },
  {
    id: 16,
    image:
      "https://w7.pngwing.com/pngs/507/528/png-transparent-paper-doll-victorian-era-dress-dress-fashion-vintage-clothing-doll.png",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 157,
    new: "Sales -22 %",
    fav: false,
    number: 0,
    color: "productCard-flex-sale",
    categorie: "Outlet",
  },
];
export default OutletData;
